### ISSUE TITLE
Wrong Pokemon Displayed on Mini Map

### ISSUE THREAD

**Issue by TurtIeSocks** [versx/NodeTileserverCache#5]
Occasionally a mini map will be drawn with a Pokemon that has previously spawned in the exact spot instead of the Pokemon being reported in the alert.

**Comment by unseenmagik** [comment]
I have seen this also and have reported it to Versx. It is to do with using a cached tile that has a sprite on it that has been used before. 
I have also seen missing tiles (using a fixed pin image)
